sh dbcsvfun.sh Standard NSW_ADDRESS_ALIAS_psv db
sh dbcsvfun.sh Standard ACT_ADDRESS_ALIAS_psv db
sh dbcsvfun.sh Standard VIC_ADDRESS_ALIAS_psv db
sh dbcsvfun.sh Standard QLD_ADDRESS_ALIAS_psv db
sh dbcsvfun.sh Standard SA_ADDRESS_ALIAS_psv db
sh dbcsvfun.sh Standard NT_ADDRESS_ALIAS_psv db
sh dbcsvfun.sh Standard WA_ADDRESS_ALIAS_psv db
sh dbcsvfun.sh Standard TAS_ADDRESS_ALIAS_psv db
sh dbcsvfun.sh Standard OT_ADDRESS_ALIAS_psv db

sh dbcsvfun.sh Standard NSW_ADDRESS_DEFAULT_GEOCODE_psv db
sh dbcsvfun.sh Standard ACT_ADDRESS_DEFAULT_GEOCODE_psv db
sh dbcsvfun.sh Standard VIC_ADDRESS_DEFAULT_GEOCODE_psv db
sh dbcsvfun.sh Standard QLD_ADDRESS_DEFAULT_GEOCODE_psv db
sh dbcsvfun.sh Standard SA_ADDRESS_DEFAULT_GEOCODE_psv db
sh dbcsvfun.sh Standard NT_ADDRESS_DEFAULT_GEOCODE_psv db
sh dbcsvfun.sh Standard WA_ADDRESS_DEFAULT_GEOCODE_psv db
sh dbcsvfun.sh Standard TAS_ADDRESS_DEFAULT_GEOCODE_psv db
sh dbcsvfun.sh Standard OT_ADDRESS_DEFAULT_GEOCODE_psv db

sh dbcsvfun.sh Standard NSW_ADDRESS_DETAIL_psv db
sh dbcsvfun.sh Standard ACT_ADDRESS_DETAIL_psv db
sh dbcsvfun.sh Standard VIC_ADDRESS_DETAIL_psv db
sh dbcsvfun.sh Standard QLD_ADDRESS_DETAIL_psv db
sh dbcsvfun.sh Standard SA_ADDRESS_DETAIL_psv db
sh dbcsvfun.sh Standard NT_ADDRESS_DETAIL_psv db
sh dbcsvfun.sh Standard WA_ADDRESS_DETAIL_psv db
sh dbcsvfun.sh Standard TAS_ADDRESS_DETAIL_psv db
sh dbcsvfun.sh Standard OT_ADDRESS_DETAIL_psv db

sh dbcsvfun.sh Standard NSW_ADDRESS_FEATURE_psv db
sh dbcsvfun.sh Standard ACT_ADDRESS_FEATURE_psv db
sh dbcsvfun.sh Standard VIC_ADDRESS_FEATURE_psv db
sh dbcsvfun.sh Standard QLD_ADDRESS_FEATURE_psv db
sh dbcsvfun.sh Standard SA_ADDRESS_FEATURE_psv db
sh dbcsvfun.sh Standard NT_ADDRESS_FEATURE_psv db
sh dbcsvfun.sh Standard WA_ADDRESS_FEATURE_psv db
sh dbcsvfun.sh Standard TAS_ADDRESS_FEATURE_psv db
sh dbcsvfun.sh Standard OT_ADDRESS_FEATURE_psv db

sh dbcsvfun.sh Standard NSW_ADDRESS_GEOCODE_psv db
sh dbcsvfun.sh Standard ACT_ADDRESS_GEOCODE_psv db
sh dbcsvfun.sh Standard VIC_ADDRESS_GEOCODE_psv db
sh dbcsvfun.sh Standard QLD_ADDRESS_GEOCODE_psv db
sh dbcsvfun.sh Standard SA_ADDRESS_GEOCODE_psv db
sh dbcsvfun.sh Standard NT_ADDRESS_GEOCODE_psv db
sh dbcsvfun.sh Standard WA_ADDRESS_GEOCODE_psv db
sh dbcsvfun.sh Standard TAS_ADDRESS_GEOCODE_psv db
sh dbcsvfun.sh Standard OT_ADDRESS_GEOCODE_psv db

sh dbcsvfun.sh Standard NSW_ADDRESS_MESH_BLOCK_2011_psv db
sh dbcsvfun.sh Standard ACT_ADDRESS_MESH_BLOCK_2011_psv db
sh dbcsvfun.sh Standard VIC_ADDRESS_MESH_BLOCK_2011_psv db
sh dbcsvfun.sh Standard QLD_ADDRESS_MESH_BLOCK_2011_psv db
sh dbcsvfun.sh Standard SA_ADDRESS_MESH_BLOCK_2011_psv db
sh dbcsvfun.sh Standard NT_ADDRESS_MESH_BLOCK_2011_psv db
sh dbcsvfun.sh Standard WA_ADDRESS_MESH_BLOCK_2011_psv db
sh dbcsvfun.sh Standard TAS_ADDRESS_MESH_BLOCK_2011_psv db
sh dbcsvfun.sh Standard OT_ADDRESS_MESH_BLOCK_2011_psv db

sh dbcsvfun.sh Standard NSW_ADDRESS_MESH_BLOCK_2016_psv db
sh dbcsvfun.sh Standard ACT_ADDRESS_MESH_BLOCK_2016_psv db
sh dbcsvfun.sh Standard VIC_ADDRESS_MESH_BLOCK_2016_psv db
sh dbcsvfun.sh Standard QLD_ADDRESS_MESH_BLOCK_2016_psv db
sh dbcsvfun.sh Standard SA_ADDRESS_MESH_BLOCK_2016_psv db
sh dbcsvfun.sh Standard NT_ADDRESS_MESH_BLOCK_2016_psv db
sh dbcsvfun.sh Standard WA_ADDRESS_MESH_BLOCK_2016_psv db
sh dbcsvfun.sh Standard TAS_ADDRESS_MESH_BLOCK_2016_psv db
sh dbcsvfun.sh Standard OT_ADDRESS_MESH_BLOCK_2016_psv db

sh dbcsvfun.sh Standard NSW_ADDRESS_SITE_GEOCODE_psv db
sh dbcsvfun.sh Standard ACT_ADDRESS_SITE_GEOCODE_psv db
sh dbcsvfun.sh Standard VIC_ADDRESS_SITE_GEOCODE_psv db
sh dbcsvfun.sh Standard QLD_ADDRESS_SITE_GEOCODE_psv db
sh dbcsvfun.sh Standard SA_ADDRESS_SITE_GEOCODE_psv db
sh dbcsvfun.sh Standard NT_ADDRESS_SITE_GEOCODE_psv db
sh dbcsvfun.sh Standard WA_ADDRESS_SITE_GEOCODE_psv db
sh dbcsvfun.sh Standard TAS_ADDRESS_SITE_GEOCODE_psv db
sh dbcsvfun.sh Standard OT_ADDRESS_SITE_GEOCODE_psv db

sh dbcsvfun.sh Standard NSW_ADDRESS_SITE_psv db
sh dbcsvfun.sh Standard ACT_ADDRESS_SITE_psv db
sh dbcsvfun.sh Standard VIC_ADDRESS_SITE_psv db
sh dbcsvfun.sh Standard QLD_ADDRESS_SITE_psv db
sh dbcsvfun.sh Standard SA_ADDRESS_SITE_psv db
sh dbcsvfun.sh Standard NT_ADDRESS_SITE_psv db
sh dbcsvfun.sh Standard WA_ADDRESS_SITE_psv db
sh dbcsvfun.sh Standard TAS_ADDRESS_SITE_psv db
sh dbcsvfun.sh Standard OT_ADDRESS_SITE_psv db

sh dbcsvfun.sh Standard NSW_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard ACT_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard VIC_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard QLD_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard SA_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard NT_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard WA_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard TAS_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard OT_LOCALITY_ALIAS_psv db

sh dbcsvfun.sh Standard NSW_LOCALITY_NEIGHBOUR_psv db
sh dbcsvfun.sh Standard ACT_LOCALITY_NEIGHBOUR_psv db
sh dbcsvfun.sh Standard VIC_LOCALITY_NEIGHBOUR_psv db
sh dbcsvfun.sh Standard QLD_LOCALITY_NEIGHBOUR_psv db
sh dbcsvfun.sh Standard SA_LOCALITY_NEIGHBOUR_psv db
sh dbcsvfun.sh Standard NT_LOCALITY_NEIGHBOUR_psv db
sh dbcsvfun.sh Standard WA_LOCALITY_NEIGHBOUR_psv db
sh dbcsvfun.sh Standard TAS_LOCALITY_NEIGHBOUR_psv db
sh dbcsvfun.sh Standard OT_LOCALITY_NEIGHBOUR_psv db

sh dbcsvfun.sh Standard NSW_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard ACT_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard VIC_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard QLD_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard SA_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard NT_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard WA_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard TAS_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard OT_LOCALITY_POINT_psv db

sh dbcsvfun.sh Standard NSW_LOCALITY_psv db
sh dbcsvfun.sh Standard ACT_LOCALITY_psv db
sh dbcsvfun.sh Standard VIC_LOCALITY_psv db
sh dbcsvfun.sh Standard QLD_LOCALITY_psv db
sh dbcsvfun.sh Standard SA_LOCALITY_psv db
sh dbcsvfun.sh Standard NT_LOCALITY_psv db
sh dbcsvfun.sh Standard WA_LOCALITY_psv db
sh dbcsvfun.sh Standard TAS_LOCALITY_psv db
sh dbcsvfun.sh Standard OT_LOCALITY_psv db

sh dbcsvfun.sh Standard NSW_MB_2011_psv db
sh dbcsvfun.sh Standard ACT_MB_2011_psv db
sh dbcsvfun.sh Standard VIC_MB_2011_psv db
sh dbcsvfun.sh Standard QLD_MB_2011_psv db
sh dbcsvfun.sh Standard SA_MB_2011_psv db
sh dbcsvfun.sh Standard NT_MB_2011_psv db
sh dbcsvfun.sh Standard WA_MB_2011_psv db
sh dbcsvfun.sh Standard TAS_MB_2011_psv db
sh dbcsvfun.sh Standard OT_MB_2011_psv db

sh dbcsvfun.sh Standard NSW_MB_2016_psv db
sh dbcsvfun.sh Standard ACT_MB_2016_psv db
sh dbcsvfun.sh Standard VIC_MB_2016_psv db
sh dbcsvfun.sh Standard QLD_MB_2016_psv db
sh dbcsvfun.sh Standard SA_MB_2016_psv db
sh dbcsvfun.sh Standard NT_MB_2016_psv db
sh dbcsvfun.sh Standard WA_MB_2016_psv db
sh dbcsvfun.sh Standard TAS_MB_2016_psv db
sh dbcsvfun.sh Standard OT_MB_2016_psv db

sh dbcsvfun.sh Standard NSW_PRIMARY_SECONDARY_psv db
sh dbcsvfun.sh Standard ACT_PRIMARY_SECONDARY_psv db
sh dbcsvfun.sh Standard VIC_PRIMARY_SECONDARY_psv db
sh dbcsvfun.sh Standard QLD_PRIMARY_SECONDARY_psv db
sh dbcsvfun.sh Standard SA_PRIMARY_SECONDARY_psv db
sh dbcsvfun.sh Standard NT_PRIMARY_SECONDARY_psv db
sh dbcsvfun.sh Standard WA_PRIMARY_SECONDARY_psv db
sh dbcsvfun.sh Standard TAS_PRIMARY_SECONDARY_psv db
sh dbcsvfun.sh Standard OT_PRIMARY_SECONDARY_psv db

sh dbcsvfun.sh Standard NSW_STATE_psv db
sh dbcsvfun.sh Standard ACT_STATE_psv db
sh dbcsvfun.sh Standard VIC_STATE_psv db
sh dbcsvfun.sh Standard QLD_STATE_psv db
sh dbcsvfun.sh Standard SA_STATE_psv db
sh dbcsvfun.sh Standard NT_STATE_psv db
sh dbcsvfun.sh Standard WA_STATE_psv db
sh dbcsvfun.sh Standard TAS_STATE_psv db
sh dbcsvfun.sh Standard OT_STATE_psv db

sh dbcsvfun.sh Standard NSW_STREET_LOCALITY_psv db
sh dbcsvfun.sh Standard ACT_STREET_LOCALITY_psv db
sh dbcsvfun.sh Standard VIC_STREET_LOCALITY_psv db
sh dbcsvfun.sh Standard QLD_STREET_LOCALITY_psv db
sh dbcsvfun.sh Standard SA_STREET_LOCALITY_psv db
sh dbcsvfun.sh Standard NT_STREET_LOCALITY_psv db
sh dbcsvfun.sh Standard WA_STREET_LOCALITY_psv db
sh dbcsvfun.sh Standard TAS_STREET_LOCALITY_psv db
sh dbcsvfun.sh Standard OT_STREET_LOCALITY_psv db

sh dbcsvfun.sh Standard NSW_STREET_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard ACT_STREET_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard VIC_STREET_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard QLD_STREET_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard SA_STREET_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard NT_STREET_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard WA_STREET_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard TAS_STREET_LOCALITY_POINT_psv db
sh dbcsvfun.sh Standard OT_STREET_LOCALITY_POINT_psv db

sh dbcsvfun.sh Standard NSW_STREET_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard ACT_STREET_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard VIC_STREET_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard QLD_STREET_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard SA_STREET_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard NT_STREET_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard WA_STREET_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard TAS_STREET_LOCALITY_ALIAS_psv db
sh dbcsvfun.sh Standard OT_STREET_LOCALITY_ALIAS_psv db

sh dbcsvfun.sh Authority_Code Authority_Code_ADDRESS_CHANGE_TYPE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_STREET_TYPE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_GEOCODE_TYPE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_ADDRESS_TYPE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_MB_MATCH_CODE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_FLAT_TYPE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_GEOCODE_RELIABILITY_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_GEOCODED_LEVEL_TYPE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_ADDRESS_ALIAS_TYPE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_LEVEL_TYPE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_STREET_SUFFIX_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_LOCALITY_CLASS_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_LOCALITY_CLASS_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_PS_JOIN_TYPE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_LOCALITY_ALIAS_TYPE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_STREET_LOCALITY_ALIAS_TYPE_AUT_psv db
sh dbcsvfun.sh Authority_Code Authority_Code_STREET_CLASS_AUT_psv db
